#!/usr/bin/env bash
# Display username, UID, and home directory from /etc/passwd

while read line; do
    username=$(echo "$line" | cut -d ":" -f1)
    uid=$(echo "$line" | cut -d ":" -f3)
    home=$(echo "$line" | cut -d ":" -f6)
    echo "$username:$uid:$home"
done < /etc/passwd

