#!/usr/bin/env bash
#kilsiz kill
pid=$(pgrep -f "4-to_infinity_and_beyond")

# If the process is found, send SIGTERM to stop it gracefully
if [ -n "$pid" ]; then
    pkill -f "4-to_infinity_and_beyond"
fi
